# -*- coding: utf-8 -*-
"""Python_dics_&_roll.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1EjSbOVZz9TaKEYAbr9uYLsP08TEQhWiU
"""

import random
while True:

  Choice= input("Roll the Dice(Y/N): ")
  if Choice =='Y'or Choice == 'y':
    Die1= random.randint(1,6)
    Die2= random.randint(1,6)
    print(f'{Die1} and {Die2}')
  elif Choice =='n' or Choice =='N':
    print("Thank you")
    break
  else:
      print("Invalid Input")

